Pro 4 email sending survey
campforce/property-management pull request #28
Opened 2022-07-28 14:29 UTC by GulzatB

2022-07-28 14:31 UTC, GulzatB commented
Kindly ask you to look through my code, pls.

2022-07-29 07:30 UTC, belekomurzakov requested changes

2022-07-29 07:30 UTC, belekomurzakov commented on force-app/main/default/classes/CaseService.cls
> +                EmailService.send(singleCase.Status);
pls push ur new changes with singleCase.SuppliedEmail

2022-07-29 08:01 UTC, GulzatB commented on force-app/main/default/classes/CaseService.cls
> +                EmailService.send(singleCase.Status);
I've pushed.

2022-07-29 08:11 UTC, belekomurzakov approved these changes
Looks great, pls merge

2022-07-29 08:23 UTC, merged

2022-07-29 08:25 UTC, GulzatB commented
How about @test?